package com.moviecatalogservice.utils;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Movies.proto

public interface responseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result = 1;</code>
   */
  java.lang.String getResult();

  /**
   * <code>string result = 1;</code>
   */
  com.google.protobuf.ByteString getResultBytes();
}
