package com.moviecatalogservice.utils;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Movies.proto

public interface requestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.topMovies movie = 1;</code>
   */
  boolean hasMovie();

  /**
   * <code>.topMovies movie = 1;</code>
   */
  topMovies getMovie();

  /**
   * <code>.topMovies movie = 1;</code>
   */
  topMoviesOrBuilder getMovieOrBuilder();
}
