package com.moviecatalogservice.utils;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Movies.proto

public interface responseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:response)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .topMovies movie = 1;</code>
     */
    java.util.List<topMovies> getMovieList();

    /**
     * <code>repeated .topMovies movie = 1;</code>
     */
    topMovies getMovie(int index);

    /**
     * <code>repeated .topMovies movie = 1;</code>
     */
    int getMovieCount();

    /**
     * <code>repeated .topMovies movie = 1;</code>
     */
    java.util.List<? extends topMoviesOrBuilder> getMovieOrBuilderList();

    /**
     * <code>repeated .topMovies movie = 1;</code>
     */
    topMoviesOrBuilder getMovieOrBuilder(
            int index);
}
