package com.example.ratingsservice.utils;
// Generated by the protocol buffer compiler.  DO NOT EDIT!

// source: Movies.proto

public interface topMoviesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:topMovies)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string movieId = 1;</code>
   */
  java.lang.String getMovieId();

  /**
   * <code>string movieId = 1;</code>
   */
  com.google.protobuf.ByteString getMovieIdBytes();

  /**
   * <code>int64 ranting = 2;</code>
   */
  long getRanting();
}
